<?php
include(dirname(dirname(__FILE__)).'/config/config.php');
include(dirname(dirname(__FILE__)).'/config/constant.php');
include(LIB_PATH.'class.utility.php');
include(LIB_PATH.'class.mysql.php');
include(LIB_PATH.'class.user.php');
include(LIB_PATH.'class.slider.php');
include(LIB_PATH.'class.permission.php');
include(LIB_PATH.'class.registation.php');
include(LIB_PATH.'class.forgetpassword.php');
include(LIB_PATH.'class.company.php');
include(LIB_PATH.'class.tax_list.php');
include(LIB_PATH.'class.productuniform.php');
include(LIB_PATH.'class.product_type.php');
include(LIB_PATH.'class.perchaise_stock.php');
include(LIB_PATH.'class.product.php');
include(LIB_PATH.'class.sales.php');
include(LIB_PATH.'class.cashinvoice.php');
include(LIB_PATH.'class.expired_medicine.php');
include(LIB_PATH.'class.expiry_medicine.php');
include(LIB_PATH.'class.shortage_stock.php');
include(LIB_PATH.'class.sales_report.php');
include(LIB_PATH.'class.get_invoice_no.php');
?>